version: "3.9"

services:
  # Make Ollama optional for local dev
  ollama:
    profiles: ["ai"]

  # Start backend without depending on ollama by default
  backend:
    depends_on:
      - postgres
      - redis

  # Frontend keeps its defaults; ensure API base URL points to local backend
  frontend:
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080/api

